services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: bxtech
      POSTGRES_USER: bxtech
      POSTGRES_PASSWORD: bxtech
    ports:
      - "5432:5432"
    volumes:
      - bxtech_pg_data:/var/lib/postgresql/data

  api:
    build:
      context: ./backend
    environment:
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./backend:/app

volumes:
  bxtech_pg_data:

