"""Update reviews table

Revision ID: 7588c6be4a24
Revises: 3827b47f19c7
Create Date: 2026-08-04 02:53:32.059438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7588c6be4a24'
down_revision = '3827b47f19c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('reviews')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('comment',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('comment',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('title')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviews', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
