"""add reorder fields to products

Revision ID: a1b2c3d4e5f6
Revises: 2fa8037655da
Create Date: 2026-08-06 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '2fa8037655da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('minimum_stock', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('reorder_quantity', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('supplier_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'fk_products_supplier_id',
        'products',
        'suppliers',
        ['supplier_id'],
        ['id']
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_products_supplier_id', 'products', type_='foreignkey')
    op.drop_column('products', 'supplier_id')
    op.drop_column('products', 'reorder_quantity')
    op.drop_column('products', 'minimum_stock')
    # ### end Alembic commands ###
