"""add slug and active to categories

Revision ID: ba6e747f7509
Revises: be3e4960b1f3
Create Date: 2026-07-30 05:02:31.320394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba6e747f7509'
down_revision = 'be3e4960b1f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_categories_slug'), ['slug'], unique=True)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_stripe_payment_intent_id'), ['stripe_payment_intent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_stripe_session_id'), ['stripe_session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_stripe_session_id'))
        batch_op.drop_index(batch_op.f('ix_payments_stripe_payment_intent_id'))

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_slug'))
        batch_op.drop_column('active')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
